sudo: required
language: java
jdk:
- openjdk11
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8e6942744794_key -iv $encrypted_8e6942744794_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
script:
- "./gradlew build && docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT ."
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git

    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    ./set-image.sh prod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT

    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com

    git add preprod/$APP_NAME/naiserator.yaml
    git add prod/$APP_NAME/naiserator.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"

    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master

    cd ..
    fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./triggerbuild.sh helse-e2e"
env:
  global:
  - APP_NAME=spenn
  - DOCKER_IMG_NAME=navikt/spenn
  - GITHUB_APP_ID=19726
  - DOCKER_USERNAME=naviktdocker
  - secure: Tsu7neWZMMX6p+0vq8pJ5TllJK9pVqKuI9zcDj9q7mvQ35TdEjknZo4PVUnLb1yoOBvqCR2eXt+sLygBAlcPCAzsTj+vweObDzVdpGUt9JLzfvook8OrgfUjfwZrr6wd3eGl1DPK5OGNtYFiXeN85CQ89nuylZnZclypnnbHxE7TdnUD9+D/83gxrHEdGF3OyBBsHwUgaJR475a0XMU/Nc4BfJuweyeC8tnGa1e50F1OL02kK5KX+klkAt4hpYx5z/k2E9yb4adpIUa3IVWJ7O89aFoP/xNPF8f4xlY5OZzevotHXhjBI37szbMAopKi8s3Xu2NnrLqh62aVyiaiAZBZ6jGMVpKrSuuIe0S8pbQzrpfXe7wcoxe1Gx9Z4iNhRA1Bo6wrzWqJIzoGcIF9yA6GDIMOYrLTcrZvKTLPQJwykI2eTuPFgqnjNYn1ndyiU76WVdp2JDlQVK8e4Ah9kTlnNRBWSTk0Ormpog5fzSA5UDpxuei8xXQeoRjHvYZ9A3ZUgh47ou07EX86UNge39BENIkkBHKK/MgFyx/l7cklmu+ac1U/jRvKzX0loQZsooq5/YH8Ga0NJPkzLhb+2PMacrTKItH2XfFbiFRbfJjpRBBXa9VV9v5D3TufEDrJmfvla/tXE+mT1HO2N14oXzN29atwLG7ILjtSolC65gU=
