apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn
  namespace: default
spec:
  env: []
  image: docker.pkg.github.com/{{version}}
  ingresses:
    - {{ingress}}
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/isAlive
    periodSeconds: 5
    timeout: 1
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    initialDelay: 20
    path: /internal/isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: {{memorylimit}}
    requests:
      cpu: 1000m
      memory: 256Mi
  vault:
    enabled: true
  webproxy: true
  team: tbd
