management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus, health, info
      path-mapping:
        prometheus: /internal/metrics

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  application:
    name: spenn
    
jms.mq:
  enabled: true

scheduler:
  enabled: true
  tasks:
    simulering: true
    avstemming: false
    oppdrag: true

ibm:
  mq:
    queue-manager: ${MQ_QUEUE_MANAGER:QM1}
    channel: ${MQ_CHANNEL:DEV.ADMIN.SVRCONN}
    conn-name: ${MQ_HOSTNAME:localhost(1414)}
    user: ${MQ_USER:admin}
    password: ${MQ_PASSWORD:passw0rd}


oppdrag:
  queue:
    mottak: DEV.QUEUE.1
    send: DEV.QUEUE.1


oppdragstate:
  topic:
    send: spenn-oppdrag-status

avstemming:
  queue:
    send: DEV.QUEUE.1

kafka:
  offset-reset:
    enabled: false
    # 01.06.2019
    timestamp-millis: 1559340000000
  stream:
    vedtak:
      enabled: true
