management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus, health, info
      path-mapping:
        prometheus: /internal/metrics

#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/${OPPDRAG_DB_NAVN}
#    username: postgres
#    password:
#    driverClassName: org.postgresql.Driver
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    continue-on-error: true
  jooq:
    sql-dialect: H2
ibm:
  mq:
    queue-manager: ${MQ_QUEUE_MANAGER:QM1}
    channel: ${MQ_CHANNEL:DEV.ADMIN.SVRCONN}
    conn-name: ${MQ_CONN_NAME:localhost(1414)}
    user: ${MQ_USER:admin}
    password: ${MQ_PASSWORD:passw0rd}
oppdrag:
  queue:
    mottak: DEV.QUEUE.1
    send: DEV.QUEUE.1
