apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spenn
  namespace: default
  labels:
    team: tbd
spec:
  image: navikt/spenn:7117a4b
  port: 8080
  team: tbd
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 256Mi
  ingresses:
    - https://spenn.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secrets: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: http://security-token-service
