apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn
  namespace: default
spec:
  image: {{image}}:{{tag}}
  ingresses:
    - https://spenn.nais.preprod.local
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/isAlive
    periodSeconds: 5
    timeout: 1
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    initialDelay: 20
    path: /internal/isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 256Mi
  vault:
    enabled: true
  webproxy: true
  secureLogs:
    enabled: true
  team: tbd
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spenn-1
    - name: KAFKA_RAPID_TOPIC
      value: helse-rapid-v1
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
