apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{team}}
  name: spenn
  namespace: default
spec:
  image: {{image}}:{{tag}}
  ingresses:
    - https://spenn.nais.adeo.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/isAlive
    periodSeconds: 5
    timeout: 1
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    initialDelay: 20
    path: /internal/isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 256Mi
  webproxy: true
  secureLogs:
    enabled: true
  team: {{team}}

  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/envvars
        kvPath: /kv/prod/fss/spenn/default
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /kv/prod/fss/spenn/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /kv/prod/fss/spenn/default
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spenn-1
    - name: KAFKA_PRODUCER_GROUP_ID
      value: spenn-1
    - name: KAFKA_RAPID_TOPIC
      value: privat-helse-sykepenger-rapid-v1
    - name: STS_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
