name: Bygg og deploy master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: create docker tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/helse-spenn
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo $(echo $GITHUB_SHA | cut -c1-7) > .docker_tag
      - name: unit test and build
        run: ./mvnw install
      - name: blackbox test
        run: cd spenn-server; ../mvnw verify -Dtest=SpennBlackBoxTest
      - name: build docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: push docker image
        run: |
          echo "$GITHUB_REPO_TOKEN" | docker login --username "$GITHUB_REPO_USER" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          GITHUB_REPO_USER: ${{secrets.GITHUB_REPO_USER}}
      - name: deploy to dev
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          AWAIT_SECONDS: 0
        with:
          cluster: dev-fss
          team: tbd
          resources: naiserator.yml
          vars: naiserator-vars-dev.json
      - name: deploy to prod
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          AWAIT_SECONDS: 0
        with:
          cluster: prod-fss
          team: tbd
          resources: naiserator.yml
          vars: naiserator-vars-prod.json
